## snakemake parameters
units: ./config/unit_foal_sepsis_EquCabAll.txt
run_name: ../output/01_pipeline/foals_sepsis_EquCabAll/
outdir: /hpc/compgen/projects/cf-spi/cf-spi/analysis/ewesdorp/ssdna-snakemake

# AdapterRemoval
adapter_removal:
    trimqualities: True
    minquality: 10
    trimns: "--trimns"

k_mer_length: 35

database:
        #- RS
        #- EquRS
- EquAllRS
  #- EquEPRSc2
  #- EquAllEPRSc2
  #- spikeIns

db_dir: /hpc/compgen/projects/cf-spi/cf-spi/analysis/ewesdorp/make_database/

k2_threshold: [0.8]

level: S

bracken:
        read_length: 100
        threshold: 1

bracken_smpl_oi: [PC1, PC2, PC3]

# adapters
# https://teichlab.github.io/scg_lib_structs/methods_html/Illumina.html
KAPA_single_index:
  adapterP7_part1: GATCGGAAGAGCACACGTCTGAACTCCAGTCAC
  adapterP7_part2: NNCTCGTATGCCGTCTTCTGCTTG
  adapterP5: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
SRSLY_dual_index:
  adapterP7_part1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
  adapterP7_part2: ATCTCGTATGCCGTCTTCTGCTTG
  adapterP5_part1: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
  adapterP5_part2: GTGTAGATCTCGGTGGTCGCCGTATCATT
IDT384UMI_dual_index:
  adapterP7_part1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
  adapterP7_part2: ATCTCGTATGCCGTCTTCTGCTTG
  adapterP5_part1: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
  adapterP5_part2: GTGTAGATCTCGGTGGTCGCCGTATCATT
